### ISSUE TITLE
Headerbars are still borked on wayland

### ISSUE THREAD

**Issue by nickavem** [lutris/agora#63]
This [issue](https://github.com/lutris/lutris/issues/3297) was closed, but still seems to be prevalent. The only fix I have found is the environment variable mentioned there. Tested in both lutris flatpak, and fedora package.

Flatpak fix:
`sudo flatpak override --env=GDK_BACKEND=x11 net.lutris.Lutris`

Package/Binary fix:
`GDK_BACKEND=x11 lutris`

**Comment by strycore** [comment]
I've made a patch that should resolve this but I don't have Wayland. Can someone confirm the master branch no longer has the issue?

**Comment by nickavem** [comment]
> I've made a patch that should resolve this but I don't have Wayland. Can someone confirm the master branch no longer has the issue?

Just tested on GNOME Wayland. Issue is still present with no useful debug output running `lutris -d`

**Comment by fabiscafe** [comment]
Can confirm. Latest git is still broken.
